---
title: "Section B. Project Workplan"
author: "Miao Li"
format: 
  html:
    output-file: "index"
    output-ext:  "html"    
    self-contained: true
    page-layout: full
    toc: true
    toc_depth: 1
    toc-location: left
    grid: 
      body-width: 2500px
      sidebar-width: 300px
      margin-width: 150px    
editor: visual
execute: 
  echo: FALSE
---

## Part 1. Community-Driven Investments for Change (80 total)

### 1.1 Community Vision Description (10 points)

> #### 1.1.1 Community Description: (3 points)

(describe the community's resources, assets, local community characteristics, and the type of benefits the grants will provide to the community.)

The [Berkeley Lake Moultrie (BLM) Area](./Target_map.html) is a 635-square-mile region forming a ring around Lake Moultrie, located in the remote northwestern corner of Berkeley County, South Carolina. The area is bordered by another lake and the Santee River wetlands to the north, the Francis Marion National Forest to the east, swamps and woodlands to the west, and suburban communities of the Charleston metropolitan area to the south. Geographic constraints have concentrated human settlement, economic activities, and transportation within this ring around Lake Moultrie, making the highways encircling the lake the primary routes for daily commuting and emergency evacuations for the 40,000 residents. The natural barriers on three sides, combined with the lake at the center, have resulted in the region being predominantly rural and significantly underserved.

Among the 26 census block groups in the area, half have been identified as disadvantaged communities by the EJScreen tool. The remaining block groups, which do not meet the disadvantaged designation, are skewed by the presence of small clusters of lake houses. Overall, approximately 40% of the local population lives in low-income households, and over 42% are African American. The area also has an aging population, with 20.6% of residents over the age of 64, and a high disability rate of 16.3%, placing it in the 60th percentile nationally. All 10 public schools in the area are Title I schools, serving a student population with an average pupil-in-poverty rate of 75%. The inadequate school system has imposed long-term constraints on workforce development. Among the three high schools, only 20% of students are considered college-ready and less than 40% are career-ready.

existing community facilities: three community centers, multiple food pantries, and multiple faith-based organizations orchestrated by Berkeley Resource Connection Center (BRCC) owned by Trident United Way, which has been playing a critical role in providing community services with long-established partnership with local organizations, including the Volunteer Organizations Active in Disaster (VOAD)

However, this area is brimming with green energy opportunities that can benefit the local disadvantaged population. With 4.5 to 5 hours of peak sun daily, it is ideal for expanding solar energy production in residential and public building. The growing solar panel manufacturing industry and decreasing costs in South Carolina further support this potential. The area also boasts affordable land and convenient access to Charleston metropolitan economic hub, home to one of the busiest and most important ports in the U.S., via three southbound traffic arteries: US Highway 52 (US-52), US Highway 176 (US-176), and US Highway 17 Alternate (US 17 Alt). Moreover, a large portion of the BLM area was designated by the Governor as the Opportunity Zone that offers aggressive tax incentives to attract clean energy and advanced manufacturing businesses. The 4,000-acre Camp Hall Commerce Park on the area's southern border already hosts major employers like [Volvo Cars](./Volvo_location.html), BSS Global Inc., and Redwood Materials, with potential to generate thousands of jobs that reduce GHG emissions and air pollutants. The Park is quickly attracting more investors aligned with its vision of a next-generation industry park. These developments occur within the broader context of South Carolina's rapidly growing into a hub for clean energy supply chain, including electric vehicle and battery manufacturing, solar panel production, and advanced materials manufacturing.

By building resilient infrastructure, promoting clean energy use, reducing pollution, fostering a healthy school environment, and launching a robust workforce development initiative that connects schools with the local green energy industry, the local community stands to gain in several ways: a reduced energy burden, a healthier living environment, better job opportunities through direct employment in the expanding green energy sector, improved educational outcomes as schools adopt industry-relevant skills, long-term economic stability, enhanced quality of life for residents, and greater community resilience during extreme weather events and disasters.

> #### 1.1.2 Community Challenges: (4 points)

Despite the great potential, communities in the BLM area grapple with multiple mutually reinforcing challenges, including socioeconomic vulnerability, workforce development crisis, inadequate infrastructure, high energy burden, environmental and climate hazards, and health disparities.

Other than the socioeconomic vulnerabilities mentioned above, the BLM area also faces significant climate impacts, climate change risks, and localized pollution, which threaten both community well-being and long-term resilience. The region's inadequate infrastructure, combined with high energy burdens, makes it particularly vulnerable to these threats. The poor condition of public facilities and housing compounds the problem, leaving residents exposed during emergencies and extreme weather events.

The lack of a regional resilience hub, along with schools and public shelters that lack resilient power supplies and energy-efficient air filtration systems, means that even designated emergency shelters are often unable to provide a safe haven during crises. The residential housing stock is similarly vulnerable; nearly half of the 12,000 housing units are mobile homes with poor insulation and outdated utilities, contributing to low energy efficiency. This results in high energy costs for residents, with many low-income families spending up to 20% of their income on energy needs, compared to the national average. More than 20% of households in the area rely on wood for heating, which is less efficient and more polluting. Only 30% of homes use electricity as their primary heating source, making it difficult to maintain adequate comfort during extreme heat, which exceeds 90 degrees on over 80 days per year.

Environmental and climate risks further exacerbate these infrastructure and energy challenges. With over 7% of the area in a 100-year floodplain, the community is highly vulnerable to flooding events, particularly as climate change increases the frequency and severity of such occurrences. Additionally, nearly 60% of the region faces wildfire risks in the 90th percentile nationally, putting lives and property at continuous risk. The area's high exposure to hurricanes and lightning adds to the vulnerability; 11 hurricanes and 5 tropical storms have struck in the past 20 years, causing significant damage and disrupting lives. Frequent lightning---exceeding 95 instances per year---threatens the stability of the energy supply, making it even more difficult to maintain reliable power during emergencies.

Localized pollution from nearby industrial facilities further challenges community health. Facilities like the Holcim Holly Hill Cement Plant, Santee Cooper Cross Generating Station, and others contribute to toxic air emissions, resulting in air quality issues that directly affect residents' health. The region has a higher-than-average prevalence of asthma, affecting more than 11% of the population, alongside elevated obesity rates of 42% to 52% across various census tracts. These health issues, coupled with a lack of accessible healthcare, make residents particularly vulnerable to pollution-related illnesses and climate impacts.

Priority populations---such as low-income households, individuals with disabilities (18% of the population), and those living in food deserts---are acutely impacted by these challenges. Around 75% of the area qualifies as a food desert, where many residents lack access to a vehicle and live far from grocery stores, further compounding issues of food insecurity. These vulnerabilities limit the community's ability to adapt to climate risks, secure stable housing, and maintain consistent access to essential services. The intersection of economic hardship, poor infrastructure, and environmental risks means that without targeted intervention, these populations will continue to face disproportionate impacts from climate change, pollution, and extreme weather events. Addressing these needs is essential for fostering resilience and improving quality of life in the BLM area.

the are is also experiencing a **workforce development crisis**, driven by an underfunded school system. Only 20% of high school students are considered college-ready and less than 40% are career-ready. Additionally, less than 11% have completed a Career and Technical Education (CTE) program or earned industry-recognized certifications. Unfortunately, the future workforce outlook is bleak, as students in the elementary and middle schools show little improvement in academic performances. For example, less than 15% of middle schoolers meet or exceed expectations in math, 22% in science, and 36% in English. The area's low-quality workforce pipeline starkly contrasts with the burgeoning green industrial development opportunities in its immediate vicinity and in South Carolina in general. A well planned and coordinated workforce development strategy can bridge \[\].

Meanwhile, the region's **inadequate infrastructure and high energy burdens** pose significant resilience challenges for both the community and individual households. The lack of a regional resilience hub, coupled with the poor condition of school and residential buildings, creates a precarious environment for residents during emergencies. Despite being designated as public emergency shelters, three of the schools in the area lacked resilient power supplies and energy-efficient air filtration systems, compromising their ability to provide safe and comfortable environments during emergencies. Residential buildings also face challenges. Of a total of 12,000 housing units, nearly half are mobile homes that suffer from poor insulation and outdated utilities, leading to low energy efficiency. Moreover, high energy costs, particularly for low-income families, place an undue financial burden on households and limit their ability to access essential services. Only 30% of homes use electricity as their primary heating source, and on average a household spends more than 10% of its total income on energy. For low-income families, the energy burden can reach as high as 20%, with over 20% of these households relying on wood for heating. The region's extreme heat, with over 80 days annually above 90 degrees, exacerbates these challenges.

Additionally, the region faces a range of **environmental and climate risks** that threaten both its ecosystem and community safety. More than 7% of the land lies within the 100-year floodplain, increasing the community's vulnerability to flooding events. Nearly 60% of the region is classified as having wildfire risk above the 90^th^ national percentile. The community is rated high or very high in both National Risk and Social Vulnerability, while its Community Resilience Rating remains moderate to low. Particularly, this area faces very high risk of Hurricane and lightening. For instance, 11 hurricanes and 5 tropical storms were [recorded](https://www.dnr.sc.gov/climate/sco/hurricanes/#map) in the past 20 years, causing various levels of damages. Other than strong winds and precipitation from hurricanes and tropic storms, the average annualized frequency of lightening in this area exceeds 95 times/yr, posing significant threat to stable energy supply. Finally, several facilities in and around the area contribute to toxic air emissions, including the Holcim Holly Hill Cement Plant, CR Bard, Inc., Santee Cooper Cross Generating Station, Giant Cement Co., Dorchester Biomass LLC, and Argos Cement LLC Harleyville Cement Plant.

**Finally, Health disparities (to be finished...)**. There is a higher-than-average prevalence of current asthma, with more than 11% of the population affected, exceeding national averages. the obesity rates range from 42% to 52% for different census tracts. The obesity rates vary between 42% and 52% across different census tracts in this area. 18% of the area's population has a disability. Finally, 75% of the area is classified as a food desert, where many households lack access to a vehicle and live more than half a mile from the nearest supermarket, or they reside more than 20 miles from the closest grocer

> #### 1.1.3 Community Vision: (3 points)

We plan to use the grant to support strategies that build climate resilience, improve energy efficiency, and foster economic growth in the BLM community. These strategies include establishing a network of community resilience hubs powered by renewable energy and storage systems, replacing outdated HVAC systems and installing air purification systems in schools, and launching a workforce development program that aligns local high school curricula with industry needs. Additionally, the grant will fund weatherization and energy efficiency upgrades for 250 low-income households and provide solar panel installations to reduce energy costs and enhance energy resilience for residents.

These strategies will deliver both immediate and long-term benefits to the BLM community by addressing critical needs, reducing pollution, and fostering economic growth. In the short term, replacing outdated HVAC systems and installing air purification in schools will improve air quality, benefiting children and vulnerable populations. Weatherization and energy efficiency upgrades for 250 low-income households, along with solar panel installations, will reduce energy costs and emissions, easing the financial burden on families. The workforce development program will align high school training with industry needs, creating pathways to well-paying jobs in the clean energy sector.

Long-term, the establishment of community resilience hubs powered by renewable energy will enhance the community's ability to withstand climate-related disruptions, ensuring access to essential services during emergencies. This, along with a sustained focus on clean energy, will reduce the region's carbon footprint and promote environmental sustainability. The workforce initiative will ensure that new job opportunities remain local, attracting further investment and creating a stable economic base. By directly involving residents in these efforts, the grant will empower the community to thrive, ensuring that the benefits of these investments are felt across generations.

# 

------------------------------------------------------------------------

### 1.2 Selected Strategies: (45 points total).

> #### 1.2.1 Strategy Overview -- (15 points)

Addressing the critical need for intelligent and resilient energy solutions is vital to fostering environmental justice, achieving sustainability, and enhancing population health. In response to the aforementioned community challenges in the BLM area, we propose a comprehensive package of strategies to bolster energy resilience, improving environmental conditions, and promoting better health outcomes for our target community. Our primary objectives are to empower the community by ensuring energy security, advancing environmental justice, enhancing public health, and improve workforce preparation. To achieve these aims, we will develop and implement a suite of innovative climate action and pollution reduction strategies to generate synergistic effects.

For the climate action strategy, we propose to creating community resilience hubs powered by renewable energy and equipped with energy storage systems, weatherizing 250 low-income homes, and installing solar panels to reduce energy costs and improve energy resilience. In parallel, we will replace outdated HVAC systems and introduce advanced air purification systems in schools, contributing to better indoor air quality and healthier environments. This integrated approach is designed to complement and reinforce each element, ensuring a resilient and affordable energy supply, optimizing energy use, and reducing pollution exposure. These efforts aim to provide a healthier, more sustainable environment and empower the community to cope with the growing challenges of climate change and air pollution.

By integrating these strategies, we aim to help the community effectively cope with the growing challenges of climate change and air pollution. The requested funding amount for each strategy and associated project was determined based on the scope of work, cost of technology and installation, and projected community benefits. To ensure the effectiveness of our approach, we will allocate 70% of the funding to climate action, 20% to pollution reduction efforts, and the remaining 10% to community engagement and collective action building. Our strategies will be guided by research-based methods and multidisciplinary approaches to ensure measurable improvements in resilience, environmental quality, and public health. Through a focus on community-specific needs and systematic evaluation, we aim to address the social and infrastructural barriers that contribute to disparities in energy security, health, and resilience. This project will not only enhance the community's ability to adapt to climate risks but also empower residents to take part in a sustainable future.


#### 1.2.2 Climate Action Strategies (15 points)

Our climate action strategy will focus on 

1. Establish a network of community resilience hubs equipped with renewable energy sources and energy storage units that help build up climate resilience, food & water resilience, communication resilience, financial resilience, and health resilience.  
2. Replace the outdated HVAC system for a high school  
3. Initiate a workforce development strategy to bridge the three local high schools curriculum and training with local industries
4. Perform weatherization and energy efficiency upgrade for 250 low income households in the area, and install solar panels for the residents for reduced energy burden and improved energy resilience.


#### 1.2.3 Pollution Reduction Strategies (15 points)

Our pollution reduction strategy will focus on 

1. Install air purification systems for all public schools  
2. Install air filtration systems for 250 households.
3. Educational and public awareness promotion activities.


------------------------------------------------------------------------

### 1.3 Community Engagement and Collaborative Governance Plan: (15 points)

------------------------------------------------------------------------

### 1.4 Community Strength Plan: (10 points)
